/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpanishadsRouteImport } from './routes/upanishads'
import { Route as GitaRouteImport } from './routes/gita'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpanishadsIndexRouteImport } from './routes/upanishads.index'
import { Route as GitaIndexRouteImport } from './routes/gita.index'
import { Route as UpanishadsSlugRouteImport } from './routes/upanishads.$slug'
import { Route as GitaSlugRouteImport } from './routes/gita.$slug'

const UpanishadsRoute = UpanishadsRouteImport.update({
  id: '/upanishads',
  path: '/upanishads',
  getParentRoute: () => rootRouteImport,
} as any)
const GitaRoute = GitaRouteImport.update({
  id: '/gita',
  path: '/gita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpanishadsIndexRoute = UpanishadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpanishadsRoute,
} as any)
const GitaIndexRoute = GitaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GitaRoute,
} as any)
const UpanishadsSlugRoute = UpanishadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UpanishadsRoute,
} as any)
const GitaSlugRoute = GitaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GitaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gita': typeof GitaRouteWithChildren
  '/upanishads': typeof UpanishadsRouteWithChildren
  '/gita/$slug': typeof GitaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/gita/': typeof GitaIndexRoute
  '/upanishads/': typeof UpanishadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gita/$slug': typeof GitaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/gita': typeof GitaIndexRoute
  '/upanishads': typeof UpanishadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gita': typeof GitaRouteWithChildren
  '/upanishads': typeof UpanishadsRouteWithChildren
  '/gita/$slug': typeof GitaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/gita/': typeof GitaIndexRoute
  '/upanishads/': typeof UpanishadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gita'
    | '/upanishads'
    | '/gita/$slug'
    | '/upanishads/$slug'
    | '/gita/'
    | '/upanishads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gita/$slug' | '/upanishads/$slug' | '/gita' | '/upanishads'
  id:
    | '__root__'
    | '/'
    | '/gita'
    | '/upanishads'
    | '/gita/$slug'
    | '/upanishads/$slug'
    | '/gita/'
    | '/upanishads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GitaRoute: typeof GitaRouteWithChildren
  UpanishadsRoute: typeof UpanishadsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upanishads': {
      id: '/upanishads'
      path: '/upanishads'
      fullPath: '/upanishads'
      preLoaderRoute: typeof UpanishadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gita': {
      id: '/gita'
      path: '/gita'
      fullPath: '/gita'
      preLoaderRoute: typeof GitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upanishads/': {
      id: '/upanishads/'
      path: '/'
      fullPath: '/upanishads/'
      preLoaderRoute: typeof UpanishadsIndexRouteImport
      parentRoute: typeof UpanishadsRoute
    }
    '/gita/': {
      id: '/gita/'
      path: '/'
      fullPath: '/gita/'
      preLoaderRoute: typeof GitaIndexRouteImport
      parentRoute: typeof GitaRoute
    }
    '/upanishads/$slug': {
      id: '/upanishads/$slug'
      path: '/$slug'
      fullPath: '/upanishads/$slug'
      preLoaderRoute: typeof UpanishadsSlugRouteImport
      parentRoute: typeof UpanishadsRoute
    }
    '/gita/$slug': {
      id: '/gita/$slug'
      path: '/$slug'
      fullPath: '/gita/$slug'
      preLoaderRoute: typeof GitaSlugRouteImport
      parentRoute: typeof GitaRoute
    }
  }
}

interface GitaRouteChildren {
  GitaSlugRoute: typeof GitaSlugRoute
  GitaIndexRoute: typeof GitaIndexRoute
}

const GitaRouteChildren: GitaRouteChildren = {
  GitaSlugRoute: GitaSlugRoute,
  GitaIndexRoute: GitaIndexRoute,
}

const GitaRouteWithChildren = GitaRoute._addFileChildren(GitaRouteChildren)

interface UpanishadsRouteChildren {
  UpanishadsSlugRoute: typeof UpanishadsSlugRoute
  UpanishadsIndexRoute: typeof UpanishadsIndexRoute
}

const UpanishadsRouteChildren: UpanishadsRouteChildren = {
  UpanishadsSlugRoute: UpanishadsSlugRoute,
  UpanishadsIndexRoute: UpanishadsIndexRoute,
}

const UpanishadsRouteWithChildren = UpanishadsRoute._addFileChildren(
  UpanishadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GitaRoute: GitaRouteWithChildren,
  UpanishadsRoute: UpanishadsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
