/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValmikiRamayanaRouteImport } from './routes/valmiki-ramayana'
import { Route as UpanishadsRouteImport } from './routes/upanishads'
import { Route as ShivaPuranaRouteImport } from './routes/shiva-purana'
import { Route as GitaRouteImport } from './routes/gita'
import { Route as BrahmaPuranaRouteImport } from './routes/brahma-purana'
import { Route as BhagavataPuranaRouteImport } from './routes/bhagavata-purana'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValmikiRamayanaIndexRouteImport } from './routes/valmiki-ramayana.index'
import { Route as UpanishadsIndexRouteImport } from './routes/upanishads.index'
import { Route as ShivaPuranaIndexRouteImport } from './routes/shiva-purana.index'
import { Route as GitaIndexRouteImport } from './routes/gita.index'
import { Route as BrahmaPuranaIndexRouteImport } from './routes/brahma-purana.index'
import { Route as BhagavataPuranaIndexRouteImport } from './routes/bhagavata-purana.index'
import { Route as ValmikiRamayanaSlugRouteImport } from './routes/valmiki-ramayana.$slug'
import { Route as UpanishadsSlugRouteImport } from './routes/upanishads.$slug'
import { Route as ShivaPuranaSlugRouteImport } from './routes/shiva-purana.$slug'
import { Route as GitaSlugRouteImport } from './routes/gita.$slug'
import { Route as BrahmaPuranaSlugRouteImport } from './routes/brahma-purana.$slug'
import { Route as BhagavataPuranaSlugRouteImport } from './routes/bhagavata-purana.$slug'

const ValmikiRamayanaRoute = ValmikiRamayanaRouteImport.update({
  id: '/valmiki-ramayana',
  path: '/valmiki-ramayana',
  getParentRoute: () => rootRouteImport,
} as any)
const UpanishadsRoute = UpanishadsRouteImport.update({
  id: '/upanishads',
  path: '/upanishads',
  getParentRoute: () => rootRouteImport,
} as any)
const ShivaPuranaRoute = ShivaPuranaRouteImport.update({
  id: '/shiva-purana',
  path: '/shiva-purana',
  getParentRoute: () => rootRouteImport,
} as any)
const GitaRoute = GitaRouteImport.update({
  id: '/gita',
  path: '/gita',
  getParentRoute: () => rootRouteImport,
} as any)
const BrahmaPuranaRoute = BrahmaPuranaRouteImport.update({
  id: '/brahma-purana',
  path: '/brahma-purana',
  getParentRoute: () => rootRouteImport,
} as any)
const BhagavataPuranaRoute = BhagavataPuranaRouteImport.update({
  id: '/bhagavata-purana',
  path: '/bhagavata-purana',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValmikiRamayanaIndexRoute = ValmikiRamayanaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValmikiRamayanaRoute,
} as any)
const UpanishadsIndexRoute = UpanishadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpanishadsRoute,
} as any)
const ShivaPuranaIndexRoute = ShivaPuranaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShivaPuranaRoute,
} as any)
const GitaIndexRoute = GitaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GitaRoute,
} as any)
const BrahmaPuranaIndexRoute = BrahmaPuranaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrahmaPuranaRoute,
} as any)
const BhagavataPuranaIndexRoute = BhagavataPuranaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BhagavataPuranaRoute,
} as any)
const ValmikiRamayanaSlugRoute = ValmikiRamayanaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ValmikiRamayanaRoute,
} as any)
const UpanishadsSlugRoute = UpanishadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UpanishadsRoute,
} as any)
const ShivaPuranaSlugRoute = ShivaPuranaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShivaPuranaRoute,
} as any)
const GitaSlugRoute = GitaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GitaRoute,
} as any)
const BrahmaPuranaSlugRoute = BrahmaPuranaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrahmaPuranaRoute,
} as any)
const BhagavataPuranaSlugRoute = BhagavataPuranaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BhagavataPuranaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhagavata-purana': typeof BhagavataPuranaRouteWithChildren
  '/brahma-purana': typeof BrahmaPuranaRouteWithChildren
  '/gita': typeof GitaRouteWithChildren
  '/shiva-purana': typeof ShivaPuranaRouteWithChildren
  '/upanishads': typeof UpanishadsRouteWithChildren
  '/valmiki-ramayana': typeof ValmikiRamayanaRouteWithChildren
  '/bhagavata-purana/$slug': typeof BhagavataPuranaSlugRoute
  '/brahma-purana/$slug': typeof BrahmaPuranaSlugRoute
  '/gita/$slug': typeof GitaSlugRoute
  '/shiva-purana/$slug': typeof ShivaPuranaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/valmiki-ramayana/$slug': typeof ValmikiRamayanaSlugRoute
  '/bhagavata-purana/': typeof BhagavataPuranaIndexRoute
  '/brahma-purana/': typeof BrahmaPuranaIndexRoute
  '/gita/': typeof GitaIndexRoute
  '/shiva-purana/': typeof ShivaPuranaIndexRoute
  '/upanishads/': typeof UpanishadsIndexRoute
  '/valmiki-ramayana/': typeof ValmikiRamayanaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhagavata-purana/$slug': typeof BhagavataPuranaSlugRoute
  '/brahma-purana/$slug': typeof BrahmaPuranaSlugRoute
  '/gita/$slug': typeof GitaSlugRoute
  '/shiva-purana/$slug': typeof ShivaPuranaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/valmiki-ramayana/$slug': typeof ValmikiRamayanaSlugRoute
  '/bhagavata-purana': typeof BhagavataPuranaIndexRoute
  '/brahma-purana': typeof BrahmaPuranaIndexRoute
  '/gita': typeof GitaIndexRoute
  '/shiva-purana': typeof ShivaPuranaIndexRoute
  '/upanishads': typeof UpanishadsIndexRoute
  '/valmiki-ramayana': typeof ValmikiRamayanaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bhagavata-purana': typeof BhagavataPuranaRouteWithChildren
  '/brahma-purana': typeof BrahmaPuranaRouteWithChildren
  '/gita': typeof GitaRouteWithChildren
  '/shiva-purana': typeof ShivaPuranaRouteWithChildren
  '/upanishads': typeof UpanishadsRouteWithChildren
  '/valmiki-ramayana': typeof ValmikiRamayanaRouteWithChildren
  '/bhagavata-purana/$slug': typeof BhagavataPuranaSlugRoute
  '/brahma-purana/$slug': typeof BrahmaPuranaSlugRoute
  '/gita/$slug': typeof GitaSlugRoute
  '/shiva-purana/$slug': typeof ShivaPuranaSlugRoute
  '/upanishads/$slug': typeof UpanishadsSlugRoute
  '/valmiki-ramayana/$slug': typeof ValmikiRamayanaSlugRoute
  '/bhagavata-purana/': typeof BhagavataPuranaIndexRoute
  '/brahma-purana/': typeof BrahmaPuranaIndexRoute
  '/gita/': typeof GitaIndexRoute
  '/shiva-purana/': typeof ShivaPuranaIndexRoute
  '/upanishads/': typeof UpanishadsIndexRoute
  '/valmiki-ramayana/': typeof ValmikiRamayanaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bhagavata-purana'
    | '/brahma-purana'
    | '/gita'
    | '/shiva-purana'
    | '/upanishads'
    | '/valmiki-ramayana'
    | '/bhagavata-purana/$slug'
    | '/brahma-purana/$slug'
    | '/gita/$slug'
    | '/shiva-purana/$slug'
    | '/upanishads/$slug'
    | '/valmiki-ramayana/$slug'
    | '/bhagavata-purana/'
    | '/brahma-purana/'
    | '/gita/'
    | '/shiva-purana/'
    | '/upanishads/'
    | '/valmiki-ramayana/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bhagavata-purana/$slug'
    | '/brahma-purana/$slug'
    | '/gita/$slug'
    | '/shiva-purana/$slug'
    | '/upanishads/$slug'
    | '/valmiki-ramayana/$slug'
    | '/bhagavata-purana'
    | '/brahma-purana'
    | '/gita'
    | '/shiva-purana'
    | '/upanishads'
    | '/valmiki-ramayana'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bhagavata-purana'
    | '/brahma-purana'
    | '/gita'
    | '/shiva-purana'
    | '/upanishads'
    | '/valmiki-ramayana'
    | '/bhagavata-purana/$slug'
    | '/brahma-purana/$slug'
    | '/gita/$slug'
    | '/shiva-purana/$slug'
    | '/upanishads/$slug'
    | '/valmiki-ramayana/$slug'
    | '/bhagavata-purana/'
    | '/brahma-purana/'
    | '/gita/'
    | '/shiva-purana/'
    | '/upanishads/'
    | '/valmiki-ramayana/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BhagavataPuranaRoute: typeof BhagavataPuranaRouteWithChildren
  BrahmaPuranaRoute: typeof BrahmaPuranaRouteWithChildren
  GitaRoute: typeof GitaRouteWithChildren
  ShivaPuranaRoute: typeof ShivaPuranaRouteWithChildren
  UpanishadsRoute: typeof UpanishadsRouteWithChildren
  ValmikiRamayanaRoute: typeof ValmikiRamayanaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valmiki-ramayana': {
      id: '/valmiki-ramayana'
      path: '/valmiki-ramayana'
      fullPath: '/valmiki-ramayana'
      preLoaderRoute: typeof ValmikiRamayanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upanishads': {
      id: '/upanishads'
      path: '/upanishads'
      fullPath: '/upanishads'
      preLoaderRoute: typeof UpanishadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shiva-purana': {
      id: '/shiva-purana'
      path: '/shiva-purana'
      fullPath: '/shiva-purana'
      preLoaderRoute: typeof ShivaPuranaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gita': {
      id: '/gita'
      path: '/gita'
      fullPath: '/gita'
      preLoaderRoute: typeof GitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brahma-purana': {
      id: '/brahma-purana'
      path: '/brahma-purana'
      fullPath: '/brahma-purana'
      preLoaderRoute: typeof BrahmaPuranaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bhagavata-purana': {
      id: '/bhagavata-purana'
      path: '/bhagavata-purana'
      fullPath: '/bhagavata-purana'
      preLoaderRoute: typeof BhagavataPuranaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valmiki-ramayana/': {
      id: '/valmiki-ramayana/'
      path: '/'
      fullPath: '/valmiki-ramayana/'
      preLoaderRoute: typeof ValmikiRamayanaIndexRouteImport
      parentRoute: typeof ValmikiRamayanaRoute
    }
    '/upanishads/': {
      id: '/upanishads/'
      path: '/'
      fullPath: '/upanishads/'
      preLoaderRoute: typeof UpanishadsIndexRouteImport
      parentRoute: typeof UpanishadsRoute
    }
    '/shiva-purana/': {
      id: '/shiva-purana/'
      path: '/'
      fullPath: '/shiva-purana/'
      preLoaderRoute: typeof ShivaPuranaIndexRouteImport
      parentRoute: typeof ShivaPuranaRoute
    }
    '/gita/': {
      id: '/gita/'
      path: '/'
      fullPath: '/gita/'
      preLoaderRoute: typeof GitaIndexRouteImport
      parentRoute: typeof GitaRoute
    }
    '/brahma-purana/': {
      id: '/brahma-purana/'
      path: '/'
      fullPath: '/brahma-purana/'
      preLoaderRoute: typeof BrahmaPuranaIndexRouteImport
      parentRoute: typeof BrahmaPuranaRoute
    }
    '/bhagavata-purana/': {
      id: '/bhagavata-purana/'
      path: '/'
      fullPath: '/bhagavata-purana/'
      preLoaderRoute: typeof BhagavataPuranaIndexRouteImport
      parentRoute: typeof BhagavataPuranaRoute
    }
    '/valmiki-ramayana/$slug': {
      id: '/valmiki-ramayana/$slug'
      path: '/$slug'
      fullPath: '/valmiki-ramayana/$slug'
      preLoaderRoute: typeof ValmikiRamayanaSlugRouteImport
      parentRoute: typeof ValmikiRamayanaRoute
    }
    '/upanishads/$slug': {
      id: '/upanishads/$slug'
      path: '/$slug'
      fullPath: '/upanishads/$slug'
      preLoaderRoute: typeof UpanishadsSlugRouteImport
      parentRoute: typeof UpanishadsRoute
    }
    '/shiva-purana/$slug': {
      id: '/shiva-purana/$slug'
      path: '/$slug'
      fullPath: '/shiva-purana/$slug'
      preLoaderRoute: typeof ShivaPuranaSlugRouteImport
      parentRoute: typeof ShivaPuranaRoute
    }
    '/gita/$slug': {
      id: '/gita/$slug'
      path: '/$slug'
      fullPath: '/gita/$slug'
      preLoaderRoute: typeof GitaSlugRouteImport
      parentRoute: typeof GitaRoute
    }
    '/brahma-purana/$slug': {
      id: '/brahma-purana/$slug'
      path: '/$slug'
      fullPath: '/brahma-purana/$slug'
      preLoaderRoute: typeof BrahmaPuranaSlugRouteImport
      parentRoute: typeof BrahmaPuranaRoute
    }
    '/bhagavata-purana/$slug': {
      id: '/bhagavata-purana/$slug'
      path: '/$slug'
      fullPath: '/bhagavata-purana/$slug'
      preLoaderRoute: typeof BhagavataPuranaSlugRouteImport
      parentRoute: typeof BhagavataPuranaRoute
    }
  }
}

interface BhagavataPuranaRouteChildren {
  BhagavataPuranaSlugRoute: typeof BhagavataPuranaSlugRoute
  BhagavataPuranaIndexRoute: typeof BhagavataPuranaIndexRoute
}

const BhagavataPuranaRouteChildren: BhagavataPuranaRouteChildren = {
  BhagavataPuranaSlugRoute: BhagavataPuranaSlugRoute,
  BhagavataPuranaIndexRoute: BhagavataPuranaIndexRoute,
}

const BhagavataPuranaRouteWithChildren = BhagavataPuranaRoute._addFileChildren(
  BhagavataPuranaRouteChildren,
)

interface BrahmaPuranaRouteChildren {
  BrahmaPuranaSlugRoute: typeof BrahmaPuranaSlugRoute
  BrahmaPuranaIndexRoute: typeof BrahmaPuranaIndexRoute
}

const BrahmaPuranaRouteChildren: BrahmaPuranaRouteChildren = {
  BrahmaPuranaSlugRoute: BrahmaPuranaSlugRoute,
  BrahmaPuranaIndexRoute: BrahmaPuranaIndexRoute,
}

const BrahmaPuranaRouteWithChildren = BrahmaPuranaRoute._addFileChildren(
  BrahmaPuranaRouteChildren,
)

interface GitaRouteChildren {
  GitaSlugRoute: typeof GitaSlugRoute
  GitaIndexRoute: typeof GitaIndexRoute
}

const GitaRouteChildren: GitaRouteChildren = {
  GitaSlugRoute: GitaSlugRoute,
  GitaIndexRoute: GitaIndexRoute,
}

const GitaRouteWithChildren = GitaRoute._addFileChildren(GitaRouteChildren)

interface ShivaPuranaRouteChildren {
  ShivaPuranaSlugRoute: typeof ShivaPuranaSlugRoute
  ShivaPuranaIndexRoute: typeof ShivaPuranaIndexRoute
}

const ShivaPuranaRouteChildren: ShivaPuranaRouteChildren = {
  ShivaPuranaSlugRoute: ShivaPuranaSlugRoute,
  ShivaPuranaIndexRoute: ShivaPuranaIndexRoute,
}

const ShivaPuranaRouteWithChildren = ShivaPuranaRoute._addFileChildren(
  ShivaPuranaRouteChildren,
)

interface UpanishadsRouteChildren {
  UpanishadsSlugRoute: typeof UpanishadsSlugRoute
  UpanishadsIndexRoute: typeof UpanishadsIndexRoute
}

const UpanishadsRouteChildren: UpanishadsRouteChildren = {
  UpanishadsSlugRoute: UpanishadsSlugRoute,
  UpanishadsIndexRoute: UpanishadsIndexRoute,
}

const UpanishadsRouteWithChildren = UpanishadsRoute._addFileChildren(
  UpanishadsRouteChildren,
)

interface ValmikiRamayanaRouteChildren {
  ValmikiRamayanaSlugRoute: typeof ValmikiRamayanaSlugRoute
  ValmikiRamayanaIndexRoute: typeof ValmikiRamayanaIndexRoute
}

const ValmikiRamayanaRouteChildren: ValmikiRamayanaRouteChildren = {
  ValmikiRamayanaSlugRoute: ValmikiRamayanaSlugRoute,
  ValmikiRamayanaIndexRoute: ValmikiRamayanaIndexRoute,
}

const ValmikiRamayanaRouteWithChildren = ValmikiRamayanaRoute._addFileChildren(
  ValmikiRamayanaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BhagavataPuranaRoute: BhagavataPuranaRouteWithChildren,
  BrahmaPuranaRoute: BrahmaPuranaRouteWithChildren,
  GitaRoute: GitaRouteWithChildren,
  ShivaPuranaRoute: ShivaPuranaRouteWithChildren,
  UpanishadsRoute: UpanishadsRouteWithChildren,
  ValmikiRamayanaRoute: ValmikiRamayanaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
